// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/cryptgame/internal/ent/challenge"
	"github.com/DanielTitkov/cryptgame/internal/ent/predicate"
)

// ChallengeUpdate is the builder for updating Challenge entities.
type ChallengeUpdate struct {
	config
	hooks    []Hook
	mutation *ChallengeMutation
}

// Where appends a list predicates to the ChallengeUpdate builder.
func (cu *ChallengeUpdate) Where(ps ...predicate.Challenge) *ChallengeUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdateTime sets the "update_time" field.
func (cu *ChallengeUpdate) SetUpdateTime(t time.Time) *ChallengeUpdate {
	cu.mutation.SetUpdateTime(t)
	return cu
}

// SetChallenge sets the "challenge" field.
func (cu *ChallengeUpdate) SetChallenge(s string) *ChallengeUpdate {
	cu.mutation.SetChallenge(s)
	return cu
}

// SetText sets the "text" field.
func (cu *ChallengeUpdate) SetText(s string) *ChallengeUpdate {
	cu.mutation.SetText(s)
	return cu
}

// SetKey sets the "key" field.
func (cu *ChallengeUpdate) SetKey(s string) *ChallengeUpdate {
	cu.mutation.SetKey(s)
	return cu
}

// SetAuthor sets the "author" field.
func (cu *ChallengeUpdate) SetAuthor(s string) *ChallengeUpdate {
	cu.mutation.SetAuthor(s)
	return cu
}

// Mutation returns the ChallengeMutation object of the builder.
func (cu *ChallengeUpdate) Mutation() *ChallengeMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChallengeUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChallengeUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChallengeUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChallengeUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ChallengeUpdate) defaults() {
	if _, ok := cu.mutation.UpdateTime(); !ok {
		v := challenge.UpdateDefaultUpdateTime()
		cu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChallengeUpdate) check() error {
	if v, ok := cu.mutation.Challenge(); ok {
		if err := challenge.ChallengeValidator(v); err != nil {
			return &ValidationError{Name: "challenge", err: fmt.Errorf(`ent: validator failed for field "Challenge.challenge": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Text(); ok {
		if err := challenge.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Challenge.text": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Key(); ok {
		if err := challenge.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Challenge.key": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Author(); ok {
		if err := challenge.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Challenge.author": %w`, err)}
		}
	}
	return nil
}

func (cu *ChallengeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(challenge.Table, challenge.Columns, sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdateTime(); ok {
		_spec.SetField(challenge.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cu.mutation.Challenge(); ok {
		_spec.SetField(challenge.FieldChallenge, field.TypeString, value)
	}
	if value, ok := cu.mutation.Text(); ok {
		_spec.SetField(challenge.FieldText, field.TypeString, value)
	}
	if value, ok := cu.mutation.Key(); ok {
		_spec.SetField(challenge.FieldKey, field.TypeString, value)
	}
	if value, ok := cu.mutation.Author(); ok {
		_spec.SetField(challenge.FieldAuthor, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{challenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChallengeUpdateOne is the builder for updating a single Challenge entity.
type ChallengeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChallengeMutation
}

// SetUpdateTime sets the "update_time" field.
func (cuo *ChallengeUpdateOne) SetUpdateTime(t time.Time) *ChallengeUpdateOne {
	cuo.mutation.SetUpdateTime(t)
	return cuo
}

// SetChallenge sets the "challenge" field.
func (cuo *ChallengeUpdateOne) SetChallenge(s string) *ChallengeUpdateOne {
	cuo.mutation.SetChallenge(s)
	return cuo
}

// SetText sets the "text" field.
func (cuo *ChallengeUpdateOne) SetText(s string) *ChallengeUpdateOne {
	cuo.mutation.SetText(s)
	return cuo
}

// SetKey sets the "key" field.
func (cuo *ChallengeUpdateOne) SetKey(s string) *ChallengeUpdateOne {
	cuo.mutation.SetKey(s)
	return cuo
}

// SetAuthor sets the "author" field.
func (cuo *ChallengeUpdateOne) SetAuthor(s string) *ChallengeUpdateOne {
	cuo.mutation.SetAuthor(s)
	return cuo
}

// Mutation returns the ChallengeMutation object of the builder.
func (cuo *ChallengeUpdateOne) Mutation() *ChallengeMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ChallengeUpdate builder.
func (cuo *ChallengeUpdateOne) Where(ps ...predicate.Challenge) *ChallengeUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChallengeUpdateOne) Select(field string, fields ...string) *ChallengeUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Challenge entity.
func (cuo *ChallengeUpdateOne) Save(ctx context.Context) (*Challenge, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChallengeUpdateOne) SaveX(ctx context.Context) *Challenge {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChallengeUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChallengeUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ChallengeUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdateTime(); !ok {
		v := challenge.UpdateDefaultUpdateTime()
		cuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChallengeUpdateOne) check() error {
	if v, ok := cuo.mutation.Challenge(); ok {
		if err := challenge.ChallengeValidator(v); err != nil {
			return &ValidationError{Name: "challenge", err: fmt.Errorf(`ent: validator failed for field "Challenge.challenge": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Text(); ok {
		if err := challenge.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Challenge.text": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Key(); ok {
		if err := challenge.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Challenge.key": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Author(); ok {
		if err := challenge.AuthorValidator(v); err != nil {
			return &ValidationError{Name: "author", err: fmt.Errorf(`ent: validator failed for field "Challenge.author": %w`, err)}
		}
	}
	return nil
}

func (cuo *ChallengeUpdateOne) sqlSave(ctx context.Context) (_node *Challenge, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(challenge.Table, challenge.Columns, sqlgraph.NewFieldSpec(challenge.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Challenge.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, challenge.FieldID)
		for _, f := range fields {
			if !challenge.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != challenge.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdateTime(); ok {
		_spec.SetField(challenge.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.Challenge(); ok {
		_spec.SetField(challenge.FieldChallenge, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Text(); ok {
		_spec.SetField(challenge.FieldText, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Key(); ok {
		_spec.SetField(challenge.FieldKey, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Author(); ok {
		_spec.SetField(challenge.FieldAuthor, field.TypeString, value)
	}
	_node = &Challenge{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{challenge.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
