// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Challenge is the predicate function for challenge builders.
type Challenge func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
